//
//  StatementModels.swift
//  santander-test-clean-swift
//
//  Created by Cesar Giupponi Paiva on 12/04/19.
//  Copyright (c) 2019 Cesar Paiva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Statements
{
  // MARK: Use cases
  
    enum Data {
        
        struct Request {
            var userId: String
        }
        
        struct Response: Codable {
            var statementList: [Statement]?
            var error: Error?
        }
        
        struct Statement: Codable {
            var title: String?
            var desc: String?
            var date: String?
            var value: Double = Double()
        }
    }
}
