//
//  StatementWorker.swift
//  santander-test-clean-swift
//
//  Created by Cesar Giupponi Paiva on 12/04/19.
//  Copyright (c) 2019 Cesar Paiva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class StatementWorker {
    
    let url: String = "https://bank-app-test.herokuapp.com/api/statements"
    
    func requestStatements(userId: String, responseData: @escaping(_ response: Statements.Data.Response,  _ errorResponse: Error) -> ()) {
        let service: Service<Statements.Data.Response> = Service(url: "\(self.url)/\(userId)")
        service.request(httpMethod: HttpMethod.GET.rawValue, parameters: nil, completion: { (response) in
            if let statements = response.statementList {
                responseData(Statements.Data.Response(statementList: statements, error: nil), Error())
            }
            
            if let error = response.error {
                responseData(Statements.Data.Response(), error)
            }
            
        }) { (failure) in
            print("error", failure)
        }
    }
}
