//
//  StatementRouter.swift
//  santander-test-clean-swift
//
//  Created by Cesar Giupponi Paiva on 12/04/19.
//  Copyright (c) 2019 Cesar Paiva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol StatementRoutingLogic {
}

protocol StatementDataPassing {
  var dataStore: StatementDataStore? { get }
}

class StatementRouter: NSObject, StatementRoutingLogic, StatementDataPassing {
  weak var viewController: StatementViewController?
  var dataStore: StatementDataStore?

}
