//
//  StatementInteractor.swift
//  santander-test-clean-swift
//
//  Created by Cesar Giupponi Paiva on 12/04/19.
//  Copyright (c) 2019 Cesar Paiva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatementBusinessLogic {
    func getStatementsByUser(userId: String)
    func getUserAccountInfo()
    func clearUserDefaults()
}

protocol StatementDataStore {
  var userAccount: LoginModel.Data.UserAccount? { get set }
}

class StatementInteractor: StatementBusinessLogic, StatementDataStore {
    
  var userAccount: LoginModel.Data.UserAccount?
    
  var presenter: StatementPresentationLogic?
  var worker: StatementWorker?
  
  // MARK: Do something
    
    func getStatementsByUser(userId: String) {
        
        worker = StatementWorker()
        worker?.requestStatements(userId: userId, responseData: { (response, error) in
            if response.statementList != nil  {
                let result = Statements.Data.Response(statementList: response.statementList, error: response.error)
                self.presenter?.reponseSuccess(response: result)
            }
            
            if response.error != nil {
                self.presenter?.responseError(response: error)
            }
        })
    }
    
    func getUserAccountInfo() {
        if let userAccountInfo = self.userAccount {
            self.presenter?.displayUserAccountInfo(userAccountInfo: userAccountInfo)
        }
    }
    
    func clearUserDefaults() {
        let userDefaults = UserDefaults.standard
        userDefaults.removeObject(forKey: "user")
        userDefaults.synchronize()
    }

}
