//
//  StatementPresenter.swift
//  santander-test-clean-swift
//
//  Created by Cesar Giupponi Paiva on 12/04/19.
//  Copyright (c) 2019 Cesar Paiva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatementPresentationLogic {
    func displayUserAccountInfo(userAccountInfo: LoginModel.Data.UserAccount)
    func reponseSuccess(response: Statements.Data.Response)
    func responseError(response: Error)
}

class StatementPresenter: StatementPresentationLogic {
    
    
  weak var statementViewController: StatementDisplayLogic?
  
    // MARK: Do something
  
    
    func reponseSuccess(response: Statements.Data.Response) {
        if let statements = response.statementList {
            self.statementViewController?.displayStatements(statement: statements)
        }
    }
    
    func responseError(response: Error) {
        self.statementViewController?.showAlert(title: "Ocorreu um erro inesperado", message: "Não foi possível carregar os lançamentos, tente novamente")
    }
    
    func displayUserAccountInfo(userAccountInfo: LoginModel.Data.UserAccount) {
        self.statementViewController?.displayUserAccountInfo(userAccountInfo: userAccountInfo)
    }
}
