//
//  LoginPresenter.swift
//  santander-test-clean-swift
//
//  Created by Cesar Giupponi Paiva on 12/04/19.
//  Copyright (c) 2019 Cesar Paiva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func showAlert(title: String, message: String)
    func reponseSuccess(response: LoginModel.Data.Response)
    func responseError(response: Error)
}

class LoginPresenter: LoginPresentationLogic {
    
    
    
    weak var loginViewController: LoginDisplayLogic?
  
    // MARK: Do something
    
    func showAlert(title: String, message: String) {
        self.loginViewController?.showAlert(title: title, message: message)
    }
    
    func reponseSuccess(response: LoginModel.Data.Response) {
        self.loginViewController?.loginSuccess(response: response)
    }
    
    func responseError(response: Error) {
        print(response)
        self.loginViewController?.showAlert(title: "Ocorreu um erro inesperado", message: "Não foi possível autenticar, tente novamente")
    }
    
    
}
