//
//  LoginModels.swift
//  santander-test-clean-swift
//
//  Created by Cesar Giupponi Paiva on 12/04/19.
//  Copyright (c) 2019 Cesar Paiva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct LoginModel
{
    // MARK: Use cases
    
    enum Data {
        
        struct Request {
            var user: String?
            var password: String?
        }
        
        struct Response: Codable {
            var userAccount: UserAccount?
            var error: Error?
        }
        
        struct UserAccount: Codable {
            var userId: Int?
            var name: String?
            var bankAccount: String?
            var agency: String?
            var balance: Double?
        }
    }
}
