//
//  LoginRouter.swift
//  santander-test-clean-swift
//
//  Created by Cesar Giupponi Paiva on 12/04/19.
//  Copyright (c) 2019 Cesar Paiva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
  func routeToShowStatements(segue: UIStoryboardSegue?)
}

protocol LoginDataPassing {
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    
  weak var loginViewController: LoginViewController?
  var dataStore: LoginDataStore?
  
  // MARK: Routing
  
  func routeToShowStatements(segue: UIStoryboardSegue?) {
    if let segue = segue {
        let destinationVC = segue.destination as! StatementViewController
        var destinationDS = destinationVC.router!.dataStore!
        passUserAccountInfo(source: dataStore!, destination: &destinationDS)
    }
  }

  // MARK: Navigation
  
  func navigateToStatementView(source: LoginViewController, destination: StatementViewController) {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passUserAccountInfo(source: LoginDataStore, destination: inout StatementDataStore) {
    destination.userAccount = source.userAccount
  }
}
